// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


let { graphql } = require("gatsby")
;

var query = (graphql`
  fragment GatsbyImageSharpFixed on ImageSharpFixed   {
    base64
    width
    height
    src
    srcSet
  }
`);

function parse(value) {
  var value$1 = value["base64"];
  return {
          base64: (value$1 == null) ? undefined : value$1,
          width: value["width"],
          height: value["height"],
          src: value["src"],
          srcSet: value["srcSet"]
        };
}

var GatsbyImageSharpFixed = {
  query: query,
  parse: parse,
  name: "GatsbyImageSharpFixed"
};

var Fragments = {
  GatsbyImageSharpFixed: GatsbyImageSharpFixed
};

export {
  Fragments ,
  
}
/*  Not a pure module */
