// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function parse(value) {
  var value$1 = value["fields"];
  var tmp;
  if (value$1 == null) {
    tmp = undefined;
  } else {
    var value$2 = value$1["slug"];
    tmp = {
      slug: (value$2 == null) ? undefined : value$2
    };
  }
  var value$3 = value["frontmatter"];
  var tmp$1;
  if (value$3 == null) {
    tmp$1 = undefined;
  } else {
    var value$4 = value$3["title"];
    tmp$1 = {
      title: (value$4 == null) ? undefined : value$4
    };
  }
  return {
          fields: tmp,
          frontmatter: tmp$1
        };
}

var query = "fragment NextPrevious on MarkdownRemark   {\nfields  {\nslug  \n}\n\nfrontmatter  {\ntitle  \n}\n\n}\n";

var name = "NextPrevious";

export {
  query ,
  parse ,
  name ,
  
}
/* No side effect */
