// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Gatsby from "gatsby";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Typography from "../utils/Typography.bs.js";

function Layout(Props) {
  var $$location = Props.location;
  var title = Props.title;
  var children = Props.children;
  var tmp = $$location.pathname === "/" ? React.createElement("h1", {
          style: ReactDOMRe.Style.combine(Typography.scale(1.5), {
                marginTop: "0px",
                marginBottom: Typography.rhythm(1.5)
              })
        }, React.createElement(Gatsby.Link, {
              children: title,
              to: "/",
              style: {
                color: "inherit",
                textDecoration: "none",
                boxShadow: "none"
              }
            })) : React.createElement("h3", {
          style: {
            fontFamily: "Montserrat, sans-serif",
            marginTop: "0px"
          }
        }, React.createElement(Gatsby.Link, {
              children: title,
              to: "/",
              style: {
                color: "inherit",
                textDecoration: "none",
                boxShadow: "none"
              }
            }));
  return React.createElement("div", {
              style: {
                marginRight: "auto",
                marginLeft: "auto",
                maxWidth: Typography.rhythm(24),
                padding: Typography.rhythm(1.5) + (" " + Typography.rhythm(3 / 4))
              }
            }, React.createElement("header", undefined, tmp), React.createElement("main", undefined, children), React.createElement("footer", undefined, "© " + (new Date().getFullYear().toString() + " Built with "), React.createElement("a", {
                      href: "https://www.gatsbyjs.org"
                    }, "Gatsby")));
}

var make = Layout;

export {
  make ,
  
}
/* react Not a pure module */
