// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Typography from "./typography";

function rhythm(prim) {
  return Typography.rhythm(prim);
}

function scale(prim) {
  return Typography.scale(prim);
}

export {
  rhythm ,
  scale ,
  
}
/* ./typography Not a pure module */
